polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'

urlpatterns = [
    path('home/',views.home,name='home'),
    path('about/',views.about, name="aboutpage"),
    path('',views.index,name='index'),
    path('<int:qstn_id>/', views.detail, name='detail'),
    path('<int:qstn_id>/', views.result,name='result'),
    path('<int:qstn_id>',views.vote,name='vote'),
    ]  

pollwebsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=300)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Question


def home(request):
    return HttpResponse('Hello this is your home page of the poll website')

def about(request):
    return HttpResponse('This is a test webpage. Thank you.')

def detail(request, question_id):
    
        question = get_object_or_404(Question, pk=question_id)
        return render(request,'polls/detail.html',{'question':question})




def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list':latest_question_list,}
    return render(request,'polls/index.html',context)





def result(request, qstn_id):
    response = 'You are loing at the results of question %s.'
    return HttpResponse(response %qstn_id)

def vote(request, qstn_id):
    return HttpResponse('you are voting on the question %s.' %qstn_id)

polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
<body>
<h1>{{ question.question_text}}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}}</li>
</ul>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<body>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</body>
</html>